angular.module('templates', ['config/templates/bootbox.partial.html', 'config/templates/checkbox.partial.html', 'config/templates/confirm.partial.html', 'config/templates/delete.partial.html', 'config/templates/layout.partial.html', 'config/templates/login.html', 'config/templates/menubar.partial.html', 'config/templates/pagination.partial.html', 'config/templates/profile.html', 'config/templates/upload.tinymce.html', 'config/templates/welcome.html', 'modules/account/templates/manager.html', 'modules/account/templates/member.html', 'modules/account/templates/seller.html', 'modules/account/templates/visitor.html', 'modules/integral/templates/exchange.html', 'modules/integral/templates/gift.html', 'modules/integral/templates/history.html', 'modules/integral/templates/poll.html', 'modules/integral/templates/project.html', 'modules/message/templates/message.html', 'modules/reserve/templates/record.html', 'modules/settings/templates/vehicle.html', 'modules/showcase/templates/goods.html']);

angular.module("config/templates/bootbox.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/bootbox.partial.html",
    "<div class=\"modal-body\" ng-bind-html=\"message|safe\"></div><div class=\"modal-footer\"><button class=\"btn btn-primary\" ng-click=\"confirm()\">确定</button> <button class=\"btn btn-default\" ng-click=\"$dismiss()\" ng-if=\"type === 'confirm'\">取消</button></div>");
}]);

angular.module("config/templates/checkbox.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/checkbox.partial.html",
    "<label class=\"checkbox-inline text-overflow\" ng-repeat=\"item in list\" title=\"{{ item[label] }}\"><input type=\"checkbox\" value=\"{{ item[value] }}\" ng-checked=\"fill.indexOf(item[value]) > -1\" ng-click=\"toggleValue(item[value])\"> {{ item[label] }}</label>");
}]);

angular.module("config/templates/confirm.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/confirm.partial.html",
    "<div class=\"modal-header\"><a class=\"close\" ng-click=\"$dismiss()\">&times;</a><h4 class=\"modal-title\">{{ title || '提示' }}</h4></div><div class=\"modal-body\" ng-bind-html=\"message|safe\"></div><div class=\"modal-footer\"><button class=\"btn btn-primary\" ng-click=\"confirm()\" ng-disabled=\"processing\">{{ confirmText || '确定' }}</button> <button class=\"btn btn-default\" ng-click=\"$dismiss()\">取消</button></div>");
}]);

angular.module("config/templates/delete.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/delete.partial.html",
    "<div class=\"modal-header\"><a class=\"close\" ng-click=\"$dismiss()\">&times;</a><h4 class=\"modal-title\">{{ title || '警告' }}</h4></div><div class=\"modal-body\" ng-bind-html=\"message|safe\"></div><div class=\"modal-footer\"><button class=\"btn btn-danger\" ng-click=\"confirm()\" ng-disabled=\"item.deleting\">{{ confirmText || '删除' }}</button> <button class=\"btn btn-default\" ng-click=\"$dismiss()\">取消</button></div>");
}]);

angular.module("config/templates/layout.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/layout.partial.html",
    "<div ng-if=\"$loaded &amp;&amp; !$layout\"><div growl></div><div ui-view></div></div><div ng-if=\"$loaded &amp;&amp; $layout &amp;&amp; member\"><header id=\"header\"><div class=\"container-fluid\"><a href=\"/\" class=\"brand link-white pull-left\"><img ng-src=\"{{ shost}}/vendor/images/logo.png\" class=\"logo\" alt=\"永佳\"> 永佳管理后台</a><div class=\"settings pull-right\"><span class=\"dropdown\"><a class=\"dropdown-toggle link-white\" href=\"\"><span class=\"text-right name\">{{ member.name }}</span> <span class=\"caret\"></span></a><ul class=\"dropdown-menu pull-right\"><li><a ui-sref=\"settings\"><i class=\"fa fa-cog text-muted\"></i> 设置</a></li><li><a ui-sref=\"logout\"><i class=\"fa fa-power-off text-muted\"></i> 退出</a></li></ul></span></div></div></header><section id=\"content\"><aside class=\"sidebar\" cs-menubar></aside><div class=\"main\"><div growl></div><div ui-view></div></div></section><footer id=\"footer\"></footer></div>");
}]);

angular.module("config/templates/login.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/login.html",
    "<div id=\"login\" ng-cloak cs-animate><div class=\"content center-block\"><form method=\"post\" name=\"form\" ng-submit=\"login()\"><h3 class=\"form-title\"><img ng-src=\"{{shost}}/vendor/images/logo.png\" alt=\"logo\"> 永佳管理平台</h3><div class=\"alert alert-danger\" ng-if=\"error\"><button type=\"button\" class=\"close\" ng-click=\"$parent.error=false\" title=\"关闭\">&times;</button> <span><i class=\"fa fa-info-circle fa-lg\"></i> {{message}}</span></div><div class=\"form-group\"><div class=\"input-group\" ng-class=\"{'ng-dirty': form.name.$dirty, 'ng-valid': form.name.$valid, 'ng-invalid': form.name.$invalid}\"><div class=\"input-group-addon\"><i class=\"fa fa-envelope\"></i></div><input class=\"form-control\" type=\"text\" placeholder=\"账号\" name=\"name\" ng-model=\"name\" cs-autofill autofocus required></div><p class=\"text-danger\" ng-if=\"form.name.$dirty &amp;&amp; form.name.$invalid\"><i class=\"fa fa-exclamation-circle\"></i> 请输入您的账号</p></div><div class=\"form-group\"><div class=\"input-group\" ng-class=\"{'ng-dirty': form.pwd.$dirty, 'ng-valid': form.pwd.$valid, 'ng-invalid': form.pwd.$invalid}\"><div class=\"input-group-addon\"><i class=\"fa fa-lock\"></i></div><input class=\"form-control\" type=\"password\" placeholder=\"密码\" name=\"pwd\" ng-model=\"pwd\" cs-autofill required></div><p class=\"text-danger\" ng-if=\"form.pwd.$dirty &amp;&amp; form.pwd.$invalid\"><i class=\"fa fa-exclamation-circle\"></i> 请输入您的密码</p></div><div class=\"form-group clearfix\"><label class=\"pull-left\"><input type=\"checkbox\" name=\"remember\" ng-model=\"remember\" value=\"false\"> 保持登录</label></div><div class=\"form-group text-center\"><button class=\"btn btn-success btn-block\" type=\"submit\" ng-disabled=\"form.$invalid || processing\"><span ng-if=\"!processing\">立即登录</span> <span ng-if=\"processing\">正在登录</span></button></div></form><div class=\"copyright small text-center text-muted\">2015 &copy; 永佳 &nbsp; 京ICP备14022431号-1</div></div></div>");
}]);

angular.module("config/templates/menubar.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/menubar.partial.html",
    "<ul class=\"menus list-unstyled\"><li><a ui-sref=\"welcome\"><i class=\"fa fa-home\"></i>菜单导航</a></li><li class=\"group\" ng-repeat=\"item in menubar\" ng-click=\"toggleGroup(item)\" ng-class=\"{active: item.active}\"><a href=\"\"><i class=\"fa fa-cog\"></i>{{ item.name }} <i class=\"fa pull-right\" ng-class=\"{'fa-angle-right': !item.active, 'fa-angle-down': item.active}\"></i></a><ul class=\"sub-menu list-unstyled\" ng-click=\"$event.stopPropagation()\"><li ng-repeat=\"menu in item.menus\" ng-class=\"{active: menu.active}\" ng-click=\"toggleMenu(menu)\"><a ng-href=\"{{ menu.sref }}\" target=\"{{ menu.target || '_self' }}\">{{ menu.name }}</a></li></ul></li></ul>");
}]);

angular.module("config/templates/pagination.partial.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/pagination.partial.html",
    "<ul class=\"pagination\" ng-show=\"totalItems > 0\"><li class=\"primary\"><a>共<i class=\"text-danger\">{{ totalItems }}</i>条，<i class=\"text-danger\">{{ totalPages }}</i>页</a></li><li ng-if=\"boundaryLinks\" ng-class=\"{disabled: noPrevious()}\"><a href ng-click=\"selectPage(1)\">{{getText('first')}}</a></li><li ng-if=\"directionLinks\" ng-class=\"{disabled: noPrevious()}\"><a href ng-click=\"selectPage(page - 1)\">{{getText('previous')}}</a></li><li ng-repeat=\"page in pages track by $index\" ng-class=\"{active: page.active}\"><a href ng-click=\"selectPage(page.number)\">{{page.text}}</a></li><li ng-if=\"directionLinks\" ng-class=\"{disabled: noNext()}\"><a href ng-click=\"selectPage(page + 1)\">{{getText('next')}}</a></li><li ng-if=\"boundaryLinks\" ng-class=\"{disabled: noNext()}\"><a href ng-click=\"selectPage(totalPages)\">{{getText('last')}}</a></li></ul>");
}]);

angular.module("config/templates/profile.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/profile.html",
    "<div class=\"page-header\"><h1>账号设置</h1></div><ul class=\"nav nav-tabs\"><li class=\"active\"><a href=\"\">修改密码</a></li></ul><div style=\"width:400px;margin-top:20px\"><form class=\"form-horizontal\" name=\"form\" autocomplete=\"off\"><div class=\"form-group\"><label class=\"col-sm-4 control-label\">原始密码：</label><div class=\"col-sm-8\"><input type=\"password\" name=\"password\" ng-model=\"password\" class=\"form-control\" placeholder=\"请输入原始密码\" required></div></div><div class=\"form-group\"><label class=\"col-sm-4 control-label text-right\">新密码：</label><div class=\"col-sm-8\"><input type=\"password\" name=\"newpassword\" ng-model=\"newpassword\" class=\"form-control\" placeholder=\"请输入新密码，至少6位\" required ng-minlength=\"6\"></div></div><div class=\"form-group\"><label class=\"col-sm-4 control-label text-right\">重复密码：</label><div class=\"col-sm-8\"><input type=\"password\" name=\"repeatpassword\" ng-model=\"repeatpassword\" class=\"form-control\" placeholder=\"请再次输入新密码\" required ng-minlength=\"6\"></div></div><div class=\"form-group\"><div class=\"col-sm-offset-4 col-sm-8\"><button class=\"btn btn-primary btn-block\" ng-click=\"changePwd()\" ng-disabled=\"form.$invalid || (newpassword !== repeatpassword) || processing\"><span ng-if=\"!processing\">提交</span> <span ng-if=\"processing\">处理中...</span></button></div></div></form></div>");
}]);

angular.module("config/templates/upload.tinymce.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/upload.tinymce.html",
    "<div class=\"modal-header\"><a class=\"close\" ng-click=\"$dismiss()\">&times;</a><h4 class=\"modal-title\">上传图片</h4></div><div class=\"modal-body text-center\" style=\"min-height:180px\"><div class=\"btn btn-primary\" style=\"position: relative;margin-top:50px\">上传文件<input type=\"file\" ng-file-select=\"onFileSelect($files)\" style=\"position:absolute;top:0;left:0;right:0;bottom:0;opacity:0\"></div></div>");
}]);

angular.module("config/templates/welcome.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("config/templates/welcome.html",
    "<h2 class=\"padding text-center\">欢迎来到永佳管理后台</h2><img ng-src=\"{{ shost }}/vendor/images/logo.png\" class=\"welcome\" cs-animate>");
}]);

angular.module("modules/account/templates/manager.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/account/templates/manager.html",
    "<div class=\"page-header\"><h1>管理员</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"><form class=\"form-inline\" ng-submit=\"query()\"><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">姓名：</label><input type=\"text\" class=\"form-control\" placeholder=\"请输入姓名\" ng-model=\"name\"></div><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">手机号：</label><input type=\"tel\" class=\"form-control\" placeholder=\"请输入手机\" ng-model=\"mobile\"></div><div class=\"mb10 mr10\"><button type=\"submit\" class=\"btn btn-primary ml10\" ng-disabled=\"form.$invalid\"><i class=\"fa fa-search\"></i> 搜索</button></div></form></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 添加</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>工号</th><th>姓名</th><th>手机号</th><th>账号</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"text-right\"><a href=\"\">重置密码</a> <a href=\"\">停用</a> <a href=\"\">编辑</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/account/templates/member.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/account/templates/member.html",
    "<div class=\"page-header\"><h1>微信用户</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"><form class=\"form-inline\" ng-submit=\"query()\"><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">姓名：</label><input type=\"text\" class=\"form-control\" placeholder=\"请输入姓名\" ng-model=\"name\"></div><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">手机号：</label><input type=\"tel\" class=\"form-control\" placeholder=\"请输入手机\" ng-model=\"mobile\"></div><div class=\"mb10 mr10\"><button type=\"submit\" class=\"btn btn-primary ml10\" ng-disabled=\"form.$invalid\"><i class=\"fa fa-search\"></i> 搜索</button></div></form></div></div></div><table class=\"table table-hover\"><thead><tr><th>微信号</th><th>公众号</th><th>头像</th><th>微信昵称</th><th>openId</th><th>姓名</th><th>手机号</th><th>称呼</th><th>购车电话</th><th>车型</th><th>关注状态</th><th>绑定状态</th><th>更新时间</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/account/templates/seller.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/account/templates/seller.html",
    "<div class=\"page-header\"><h1>销售顾问</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"><form class=\"form-inline\" ng-submit=\"query()\"><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">姓名：</label><input type=\"text\" class=\"form-control\" placeholder=\"请输入姓名\" ng-model=\"name\"></div><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">手机号：</label><input type=\"tel\" class=\"form-control\" placeholder=\"请输入手机\" ng-model=\"mobile\"></div><div class=\"mb10 mr10\"><button type=\"submit\" class=\"btn btn-primary ml10\" ng-disabled=\"form.$invalid\"><i class=\"fa fa-search\"></i> 搜索</button></div></form></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 添加</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>工号</th><th>姓名</th><th>手机号</th><th>账号</th><th>头像</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"text-right\"><a href=\"\">重置密码</a> <a href=\"\">停用</a> <a href=\"\">编辑</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/account/templates/visitor.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/account/templates/visitor.html",
    "<div class=\"page-header\"><h1>潜客用户</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"><form class=\"form-inline\" ng-submit=\"query()\"><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">姓名：</label><input type=\"text\" class=\"form-control\" placeholder=\"请输入姓名\" ng-model=\"name\"></div><div class=\"form-group mb10 mr10\"><label class=\"control-label text-normal text-nowrap\">手机号：</label><input type=\"tel\" class=\"form-control\" placeholder=\"请输入手机\" ng-model=\"mobile\"></div><div class=\"mb10 mr10\"><button type=\"submit\" class=\"btn btn-primary ml10\" ng-disabled=\"form.$invalid\"><i class=\"fa fa-search\"></i> 搜索</button></div></form></div></div></div><table class=\"table table-hover\"><thead><tr><th>序列号</th><th>公众号</th><th>头像</th><th>微信昵称</th><th>openId</th><th>姓名</th><th>手机号</th><th>称呼</th><th>关注车型</th><th>购车类别</th><th>购车用途</th><th>购车预算</th><th>预计购车时间</th><th>购车方式</th><th>跟进顾问</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/integral/templates/exchange.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/integral/templates/exchange.html",
    "<div class=\"page-header\"><h1>兑换记录</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 新建资讯</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>资讯ID</th><th>资讯标题</th><th>资讯头图</th><th>创建时间</th><th>创建者</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"actions\"><a class=\"action\">下线</a> <a class=\"action\">推送</a> <a class=\"action\">编辑</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/integral/templates/gift.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/integral/templates/gift.html",
    "<div class=\"page-header\"><h1>礼品管理</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 新建资讯</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>资讯ID</th><th>资讯标题</th><th>资讯头图</th><th>创建时间</th><th>创建者</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"actions\"><a class=\"action\">下线</a> <a class=\"action\">推送</a> <a class=\"action\">编辑</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/integral/templates/history.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/integral/templates/history.html",
    "<div class=\"page-header\"><h1>积分记录</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 为客户修改积分</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>序列号</th><th>公众号</th><th>头像</th><th>微信昵称</th><th>姓名</th><th>手机</th><th>性别</th><th>是否车主</th><th>事件</th><th>+积分</th><th>-积分</th><th>积分余额</th><th>更新时间</th><th>备注</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/integral/templates/poll.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/integral/templates/poll.html",
    "<div class=\"page-header\"><h1>积分池</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 新建积分池</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>资讯ID</th><th>资讯标题</th><th>资讯头图</th><th>创建时间</th><th>创建者</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"actions\"><a class=\"action\">下线</a> <a class=\"action\">推送</a> <a class=\"action\">编辑</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/integral/templates/project.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/integral/templates/project.html",
    "<div class=\"page-header\"><h1>积分项目</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 新建资讯</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>类型</th><th>公众号</th><th>名称</th><th>积分单价</th><th>数量</th><th>积分总额</th><th>已兑换数量</th><th>余额</th><th>已赠送积分</th><th>已兑换积分</th><th>更换时间</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"actions\"><a class=\"action\">编辑</a> <a class=\"action\">下线</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/message/templates/message.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/message/templates/message.html",
    "<div class=\"page-header\"><h1>资讯管理</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 新建资讯</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>资讯ID</th><th>资讯标题</th><th>资讯头图</th><th>创建时间</th><th>创建者</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"actions\"><a class=\"action\">下线</a> <a class=\"action\">推送</a> <a class=\"action\">编辑</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/reserve/templates/record.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/reserve/templates/record.html",
    "<div class=\"page-header\"><h1>预约记录</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 为客户预约</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>序列号</th><th>头像</th><th>微信昵称</th><th>openId</th><th>姓名</th><th>手机号</th><th>称呼</th><th>是否车主</th><th>预约项目</th><th>车辆</th><th>预约日期</th><th>到店时间</th><th>更新时间</th><th class=\"text-right\">状态</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/settings/templates/vehicle.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/settings/templates/vehicle.html",
    "<div class=\"page-header\"><h1>车型参数</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 添加</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>序列号</th><th>公众号(经销店)</th><th>车型名称</th><th>型号</th><th>参数</th><th>更新时间</th><th>社区</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item.name }}</td><td>{{ item.nick }}</td><td>{{ item.updateByName }}</td><td>{{ item.roleName }}</td><td>{{ item.mobile }}</td><td>{{ item.updateAt|date:'yyyy-MM-dd HH:mm:ss' }}</td><td><a href=\"\" ng-click=\"getRelation(item)\">查看/绑定</a></td><td>{{ item.status|status }}</td><td class=\"text-right\"><a href=\"\">停用</a> <a href=\"\">启用</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);

angular.module("modules/showcase/templates/goods.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("modules/showcase/templates/goods.html",
    "<div class=\"page-header\"><h1>展厅设置</h1></div><div class=\"filter clearfix\"><div class=\"row\"><div class=\"col-sm-9\"></div><div class=\"col-sm-3 text-right\"><a class=\"btn btn-success\" ng-click=\"create()\"><i class=\"fa fa-plus\"></i> 新增展厅车型</a></div></div></div><table class=\"table table-hover\"><thead><tr><th>序列号</th><th>公众号(经销商)</th><th>车型名称</th><th>国产/进口</th><th>指导价</th><th>头图</th><th>图库</th><th>型号</th><th>更新时间</th><th>状态</th><th class=\"text-right\">操作</th></tr></thead><tbody><tr ng-if=\"loading\"><td class=\"loading-holder\" colspan=\"40\"><div class=\"text-center\"><span class=\"loading\"></span></div></td></tr><tr ng-if=\"total === 0\"><td colspan=\"40\"><div class=\"text-center\">抱歉，没有相关数据</div></td></tr><tr ng-repeat=\"item in list\"><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td>{{ item }}</td><td class=\"actions\"><a class=\"action\">撤出</a> <a class=\"action\">修改</a></td></tr></tbody></table><div class=\"text-right\"><ul class=\"pagination-sm\" pagination ng-model=\"page\" items-per-page=\"size\" total-items=\"total\" ng-change=\"query()\"></ul></div>");
}]);
